version: "3"

services:  
  mifos-app-server:
    build:
        context: ./mifos
        dockerfile: Dockerfile
    container_name: mifos-app-server
    restart: always
    ports:
      - 8443:8443
      - 8080:8080
    networks:
      - mifos-network
    depends_on:
      - mifos-db-server
    healthcheck:
      test: curl -kfsS https://127.0.0.1:8443 | grep 'Tomcat' | wc -l 
      interval: 5s
      retries: 20

  mifos-db-server:
    build:
        context: ./mysql
        dockerfile: Dockerfile
    container_name: mifos-db-server
    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: m1f05my5ql
    healthcheck:
      test:  mysqladmin --user=root --password=m1f05my5ql ping -h localhost
      interval: 5s
      retries: 20
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - mifos-network
      - default

#Nginx Service
  mifos_nginx_webserver:
    image: nginx:alpine
    container_name: mifos_nginx_webserver
    restart: unless-stopped
    tty: true
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=${HOST_URL}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${HOST_URL}
      - LETSENCRYPT_EMAIL=${HOST_SSL_EMAIL}
    volumes:
      - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mifos-network


#phpmyadmin service
  mifos_phpmyadmin:
    links:
      - mifos-db-server
    image: phpmyadmin/phpmyadmin
    container_name: mifos_phpmyadmin
    restart: unless-stopped
    ports:
      - '8095:80'
    environment:
      PMA_PORT: 3306
      PMA_HOST: mifos-db-server
      UPLOAD_LIMIT: 1000000000
    networks:
      - default

#Docker Networks
networks:
  mifos-network:
    external:
        name: nginx-proxy

#Volumes
volumes:
  dbdata:
    driver: local
